### PR TITLE
Add poshandler for centering below point

### PR DESCRIPTION
**Pull request by yangsheng6810**
Add poshandler posframe-poshandler-point-window-center, which shows a window-centering posframe right below point

### CODE REVIEW

**Comment by tumashu** [comment]
thanks, do you signed FSF paper? for posframe is a gnu elpa package

**Comment by yangsheng6810** [comment]
Not yet, but I am happy to sign it.
Is it the correct way that I fill in the form at [request-assign-futre](https://orgmode.org/request-assign-future.txt) (replace the org-mode text), and mail it to assign@gnu.org? What will happen next?

**Comment by tumashu** [comment]
The process takes some daysto complete, but is actually simple.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html

Just send an email in your name to emacs-devel@gnu.org asking for a Copyright Assignment for an Elpa package. You will receive a small form asking basic data: Name, package you will contribute to, email and not much more. And then you'll receive a document you should print-sign-scan-emailback.

And that's it.

**Comment by yangsheng6810** [comment]
It was a long and tedious process to get FSF paper sign (horrible bureaucracy of my university), but finally get it! Fee free to merge the PR.

**Comment by tumashu** [comment]
merged, thanks

**Pull request merged**
