### PR TITLE
add center handler

### PR DESCRIPTION
**Pull request by conao3**
Hi!
I add below center handler functions
 - posframe-poshandler-frame-bottom-center
 - posframe-poshandler-window-top-center
 - posframe-poshandler-window-bottom-center

There's already existed posframe-poshandler-frame-top-center, but other center function does not exist. so I add them.

### CODE REVIEW

**Comment by tumashu** [comment]
Do you have asign FSF gpl paper?  for posframe is an elpa package

**Comment by conao3** [comment]
OK. I've asigned.

**Comment by tumashu** [comment]
merged, thanks!

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
