### PR TITLE
* posframe.el (posframe-hide): erase-buffer and redraw-frame before hide

### PR DESCRIPTION
**Pull request by tumashu**
Fix the problem: https://github.com/tumashu/ivy-posframe/pull/30

### CODE REVIEW

**Comment by blue0513** [comment]
Thx for fixing this bug 🎉   
If you don't mind, plz add us @blue0513 & @conao3 as co-authours like [this](https://help.github.com/en/articles/creating-a-commit-with-multiple-author), cuz originally we suggests this solution 👍 (we dont' care if cant'!)

**Comment by tumashu** [comment]
Use this: https://github.com/tumashu/posframe/commit/da93ec72d9b1fb24d244e3d92f0ab35f25c0e943

**Comment by tumashu** [comment]
@blue0513 @conao3  posframe is a gnu elpa package, so If you are want to contribute it, you should sign FSF paper.

**Comment by tumashu** [comment]
ivy-posframe have no this problem

**Pull request closed without merging**
