### PR TITLE
* posframe.el (posframe-poshandler-argument-builder): New function.

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by clemera** [comment]
Thank you for looking into this! The purpose I was thinking about was to make it possible to reuse the posframe position handler functions for get position data. With this PR the argument builder assumes there already is an existing child-frame. Would it make sense to also allow passing `nil` for child-frame? So one could do:


```elisp
(let ((info (posframe-poshandler-argument-builder nil)))
  (posframe-poshandler-point-bottom-left-corner info))
```
to get the position data at point bottom left corner of current frame. This works when changing the definition to the following:

```elisp
(cl-defun posframe-poshandler-argument-builder (child-frame
                                                &key
                                                position
                                                poshandler
                                                x-pixel-offset
                                                y-pixel-offset)
  "Return a list related to CHILD-FRAME, which can be used as poshandler's info argument.
The documents of POSITION, POSHANDLER, X-PIXEL-OFFSET and
Y-PIXEL-OFFSET can be found in dostring of `posframe-show'."
  (let* ((position (or position (point)))
         ;;; CHANGED START
         (frame-width (and child-frame (frame-pixel-width child-frame)))
         (frame-height (and child-frame (frame-pixel-height child-frame)))
         (frame-buffer (and child-frame (window-buffer (frame-root-window child-frame))))
         (parent-frame (if child-frame
                           (frame-parent child-frame)
                         (selected-frame)))
         ;;; CHANGED END
         (parent-frame-width (frame-pixel-width parent-frame))
         (parent-frame-height (frame-pixel-height parent-frame))
         (parent-window (frame-root-window parent-frame))
         (parent-window-top (window-pixel-top parent-window))
         (parent-window-left (window-pixel-left parent-window))
         (parent-window-width (window-pixel-width parent-window))
         (parent-window-height (window-pixel-height parent-window))
         (position-info
          (if (integerp position)
              (posn-at-point position parent-window)
            position))
         (font-width (default-font-width))
         (font-height (with-current-buffer (window-buffer parent-window)
                        (posframe--get-font-height position)))
         (mode-line-height (window-mode-line-height parent-window))
         (minibuffer-height (window-pixel-height (minibuffer-window)))
         (header-line-height (window-header-line-height parent-window))
         (tab-line-height (if (functionp 'window-tab-line-height)
                              (window-tab-line-height parent-window)
                            0)))
    (list :position position
          :position-info position-info
          :poshandler poshandler
          :font-height font-height
          :font-width font-width
          :posframe child-frame
          :posframe-width frame-width
          :posframe-height frame-height
          :posframe-buffer frame-buffer
          :parent-frame parent-frame
          :parent-frame-width parent-frame-width
          :parent-frame-height parent-frame-height
          :parent-window parent-window
          :parent-window-top parent-window-top
          :parent-window-left parent-window-left
          :parent-window-width parent-window-width
          :parent-window-height parent-window-height
          :mode-line-height mode-line-height
          :minibuffer-height minibuffer-height
          :header-line-height header-line-height
          :tab-line-height tab-line-height
          :x-pixel-offset (or x-pixel-offset 0)
          :y-pixel-offset (or y-pixel-offset 0))))
```

**Comment by tumashu** [comment]
please try again

**Comment by clemera** [comment]
Yes, thanks this works. I wonder if the handlers could be updated to receive the `info` argument optionally. Internally they could then use:

```elisp
(let ((info (or info (posframe-poshandler-argbuilder))))
  ...
```

This way one wouldn't have to know about `posframe-poshandler-argbuilder` and just call them like:

```elisp
(posframe-poshandler-point-bottom-left-corner)
```

What do you think?

**Comment by tumashu** [comment]
To do this will lost the below feature:
```
(let ((info (posframe-poshandler-argbuilder)))
  (plist-put info :position 100)
  (posframe-poshandler-point-bottom-left-corner info)
  )
```

**Comment by clemera** [comment]
If the `info` argument is optional you could still pass it like this so the above example would still work I think.

**Comment by clemera** [comment]
```elisp
(defun posframe-poshandler-point-bottom-left-corner (&optional info font-height upward)
  (let* ((info (or info (posframe-poshandler-argbuilder)))
         ...)))
```

**Comment by tumashu** [comment]
I don't perfer to do this, for posframe-poshandler-argbuilder do not work properly in some condition,for example: no child-frame, so I do not let it become bugs of  poshandler :-)

**Comment by clemera** [comment]
I see, the `posframe-poshandler-argbuilder` alone is still also a nice addition :)

**Comment by tumashu** [comment]
please try it, if no problem, I will merge it. :-)

**Comment by clemera** [comment]
I tested with all handlers and discovered are few issues:

- When using `..poshandler-frame...` position handlers the `frame-height` and `frame-height` in info need to be a number so if no child-frame is passed they should default to 0
- When there are multiple windows and no child-frame is passed `parent-window` should default to `(selected-window)` so the `...poshandler-window..` position functions work.
- The `:x-position-offset` and `:y-position-offset` seem to have no effect.

**Comment by clemera** [comment]
If that helps I used miniframe-mode for testing like this:

```elisp
(setq mini-frame-show-parameters                                        
      (lambda ()                                                                
        (let* ((info (posframe-poshandler-argbuilder))
               (posn (posframe-poshandler-window-top-center info))
               (left (car posn))
               (top (cdr posn)))
          `((left . ,left)
            (top . ,top)
            (width . 80)
            (height . 1)))))
```

**Comment by tumashu** [comment]
```
When there are multiple windows and no child-frame is passed parent-window should default to (selected-window) so the ...poshandler-window.. position functions work.
```

does  (frame-root-window (selected-frame))  not work well?

```
The :x-position-offset and :y-position-offset seem to have no effect.
```

maybe, some poshandler do not use two args

**Comment by clemera** [comment]
> does (frame-root-window (selected-frame)) not work well?

It seems it needs the window that was selected, the root window of the frame isn't the one where the position should get calculated, if you use the selected-window it works. 

> maybe, some poshandler do not use two args

Maybe these args can be removed from the arg builder to avoid confusion? If an offset is needed one could also pass a different `position`?

**Comment by tumashu** [comment]
```
Maybe these args can be removed from the arg builder to avoid confusion? If an offset is needed one could also pass a different position?
```
position's value like (point), wile  the two args is pixel,  they are different.

**Comment by tumashu** [comment]
```
It seems it needs the window that was selected, the root window of the frame isn't the one where the position should get calculated, if you use the selected-window it works.
```
maybe fixed.

**Comment by clemera** [comment]
> maybe fixed.

Yes, it works, thank you! I figured the pixel offsets works with `posframe-poshandler-point-bottom-left-corner` as you said some poshandlers don't handle it like `posframe-poshandler-window-top-center` for example. 

On last thing: If you don't pass a child-frame you might still know that the dimensions of it. For example with miniframe you can configure the width/height. The frame-buffer is only needed for internal posframe handling it seems but not for position calculation, but the frame-width and frame-height are used for position calculation. What do you think about using the following args then:

```elisp
(&key
 child-frame-width
 child-frame-height
 position
 poshandler
 x-pixel-offset
 y-pixel-offset)
```

**Comment by tumashu** [comment]
child-frame-width
 child-frame-heigh

seem to a good idea

**Comment by tumashu** [comment]
one problem is that the size will be pixel

**Comment by clemera** [comment]
Okay, then it is probably better to keep it that way, as far as I am concerned this PR can be merged, it can be used for miniframe purposes like this:

```elisp
(setq mini-frame-show-parameters                                      
      (lambda ()                                        
        (let* ((info (posframe-poshandler-argbuilder mini-frame-frame))
               (posn (posframe-poshandler-window-center info))
               (left (car posn))
               (top (cdr posn)))
          `((left . ,left)
            (top . ,top)))))
```

On initial invocation the position of the frame will be wrong as  `mini-frame-frame` has no initial size, but afterwards it works.

**Comment by clemera** [comment]
Thanks!

**Pull request merged**
