### PR TITLE
Fix for unintended background color changing. #36

### PR DESCRIPTION
**Pull request by tttuuu888**
This is fix for #36  and https://github.com/tumashu/ivy-posframe/issues/

After this, `ivy-posframe` background color will remain even if default background color is changed.

Thanks.

### CODE REVIEW

**Comment by tumashu** [comment]
by the way, do you assign gpl paper?

**Comment by tttuuu888** [comment]
@tumashu  I didn't think about it but if it is a necessary for this project? yes. Do I have to do something specifically?

**Comment by tumashu** [comment]
for posframe is a gnu elpa package, need assign gpl paper

**Comment by tttuuu888** [comment]
Is this you are talking about? https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html
It says I need to apply by e-mail and it will take several days. So.. I'm not assigned at the moment.

Then what can I do to make this pull request applied?

**Comment by tttuuu888** [comment]
@tumashu I think you can just apply this by your name. Of course only if this has no problem. 
I think this works fine though.

**Comment by tttuuu888** [comment]
I made an another pull request at `ivy-posframe` repository.(https://github.com/tumashu/ivy-posframe/pull/64)

Well, sending assignment of GPL is likely going to take long time but that's not the main reason I tried to solve this issue from `ivy-posframe` side. Please refer to the above link in details.

Thanks.

**Comment by tttuuu888** [comment]
I'm closing this pull request following @tumashu 's suggestion from https://github.com/tumashu/ivy-posframe/issues/63.
Thanks.

**Pull request closed without merging**
