### PR TITLE
Fix byte compiler and checkdoc warnings, add autoload cookie

### PR DESCRIPTION
**Pull request by stepnem**

### CODE REVIEW

**Comment by tumashu** [comment]
Thanks, by the way, do you have assign gpl paper, for posframe is gnu elpa package

**Comment by stepnem** [comment]
No, I do not have the FSF papers on file. Several years ago when asked
to sign the papers I decided not to as the procedure seemed very
problematic (mostly sending papers back and forth all over the world),
but I think they've become slightly more reasonable since then. If you
can give me instructions on where to inquire I'll certainly give it a
try as I would very much like to be able to contribute freely to GNU
projects.

**Comment by conao3** [comment]
Hi, I'm `ivy-posframe` co-maintainer.
My projects, `leaf.el`, plans to add ELPA, so all contributors must send mail to assign FSF.
My `contributinig.org` has little instructions to assign FSF. You can read it and you can use as a reference.
https://github.com/conao3/leaf.el/blob/master/CONTRIBUTING.org#copyright-assignments

**Comment by stepnem** [comment]
I'll try that and let you know, thank you.

**Comment by stepnem** [comment]
I have completed the copyright assignment.

I have now also updated the pull request branch to include the latest
commit on master.

**Comment by tumashu** [comment]
merged, thanks!

**Pull request merged**
